### ISSUE TITLE
Code does not match video

### ISSUE THREAD

**Issue by BarnettCT** [FlingOS/Getting-Started-Tutorials#1]
Getting-Started-Tutorials/2. Booting/Code/Kernel.asm
The code does not match the code in the video.
Tried typing code in but it too blurry to read.

**Comment by EdNutting** [comment]
Hi BarnettCT, 
The code for tutorials 2 and 3 was updated to simplify it after we were informed that it started too complex and didn't match the statement in the video ("the simplest code required for a bootable OS"). As a result, the code in the video no longer matches the sample code. The code in the video is part of sample code for video 4 and onwards. Sorry for the confusion. We will be updating videos 2 and 3 in the near future.

As for code being too blurry, please turn up the quality you are watching at in YouTube. This is done using the Settings Gear icon in the bottom right corner of the player and then using the drop-down to select the quality. The default chosen by YouTube is often 360p, which makes everything very blurry, but if you choose 720p or 1080p, it is fine. I have reviewed the code content of the video at 720p and find it perfectly readable at various scales. If you are using a non-standard player, watching on mobile or attempting to watch offline, then quality is likely to be affected.

If in doubt, look at the later tutorials for more complex/comprehensive sample code.

Best regards,
Ed Nutting
Founder of FlingOS
