### ISSUE TITLE
Code in video does not match code in video

### ISSUE THREAD

**Issue by BarnettCT** [FlingOS/Getting-Started-Tutorials#2]
Getting-Started-Tutorials/2. Booting/Code/Kernel.asm
I have attached screen snippets of what I am seeing. The booting tutorial shows kernel.asm contains 70 lines of code. This is at 12 minutes and 3 seconds into the tutorial. The code in the repository shows only 40 lines of code.

Would really like to complete tutorial but cannot make out some of the code in the video. The verbal instructions on the tutorial say to use code shown and that link is in the description. Where description is is not obvious to me so I attempted to get code from repository.

Sorry if I am missing something obvious.

![videocode-70lines](https://cloud.githubusercontent.com/assets/14220468/10268596/bfa194fa-6a8b-11e5-809a-ce555797f0b2.PNG)
![githubcode-40lines](https://cloud.githubusercontent.com/assets/14220468/10268595/bfa158f0-6a8b-11e5-89d3-743ed4ed77ec.PNG)

**Comment by EdNutting** [comment]
Yes the video shows out of date code which was longer. If you continue through the next two tutorials you will find the longer code is introduced then. 

The 40 lines in the repository are complete for tutorial two. If you can understand them then you have completed tutorial 2.

**Comment by BarnettCT** [comment]
Thanks
